### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by Epikem** [mbuzdalov/edx-io#1]
Could I use this library freely? I want to use this library to my code.

**Comment by mbuzdalov** [comment]
I've added the MIT license. This should not harm you much. I didn't expect that this library will be useful outside programming competitions :)

By the way, which part of the library you are going to use? Just curious.

Please be careful with the code. Although there were no issues with it during the last run of the edX course, it still may have some, which do not manifest themselves on the actual tests used in the course. I will be very grateful if you let me know in the case you find any problems.

**Comment by Epikem** [comment]
Thanks! I'm going to use this to make a python library for online judge sites.

**Comment by mbuzdalov** [comment]
If you are making up your own online judge, and you are experienced enough, a better way might be to take the C part of this library and produce a Python extension. Unfortunately I don't have so much free time to make such things.

The current pure-Python implementation, although rather easy to use, is still somewhat slower than a hand-written problem-specific reader using mmap.

Yet another concern is that you cannot really use memory-mapping if your online judge requires reading from the standard input and writing to the standard output.

**Comment by Epikem** [comment]
No I mean a tiny python template that preprocesses user code. I'm a newbie on programming so practicing by making little things.
