### ISSUE TITLE
Makefile for creating a dynamic library

### ISSUE THREAD

**Issue by YourRatzon** [mbuzdalov/edx-io#2]
Hey Max,

I really like your library and I wanted to make a C++ dynamic library out of it to link to locally. 
I had to merge the C and the C++ files since I didn't figure out how to make a library out of them separately.
Maybe you could maintain a Makefile as part of the repository, to ease this process for the future?

P.S. I am really enjoying your algorithms course on openedu.ru, I really hope there will be a second advanced class in the future!

**Comment by mbuzdalov** [comment]
Hi Yechiel,

I have just added a makefile (check the `misc` directory) which produces a shared library. It is also equipped with a basic sanity test. (And, thanks to your request, `edx-io.h` now has `extern "C"` so that linking the object files made by `gcc` and `g++` is possible).

Could you please check whether it fulfils your needs?

**Comment by YourRatzon** [comment]
Checked it and it works, thanks so much!

**Comment by mbuzdalov** [comment]
Thank you for the response, I am closing the issue now.

On the openedu.ru course. Unfortunately, I have no idea for whether there will be a follow-up course. I was notified recently that, according to the recent data analysis of the logs, the course is typically felt as overcomplicated. One of the goods solutions is to split the course into two, where the first one is prepended by a few weeks dedicated to the basics of programming, and the second one is augmented by more topics (such as graphs and computational geometry). However, I doubt I am qualified enough to make up the easy part, and I also doubt that those who are qualified will agree to participate.

**Comment by YourRatzon** [comment]
I really enjoyed your presentation, it is crystal clear and makes the subjects actually seem simple. I can see how some of the programming exercises could be difficult for those with less experience. 
Regardless, I hope there will be more one day (soon :) !
