### ISSUE TITLE
Не работает на Microsoft Visual Studio 2017

### ISSUE THREAD

**Issue by StudentIrgups** [mbuzdalov/edx-io#4]
![image](https://user-images.githubusercontent.com/47680334/53298660-79108b80-3874-11e9-88fd-843b0c8a58d0.png)

**Comment by mbuzdalov** [comment]
Забываете подключить к компиляции файлы `edx-io.cpp` и `edx-io.c`.

Без первого из них не будет операторов. Без второго не будет того, через что эти операторы работают. Добавьте эти файлы в проект так, чтобы они тоже компилировались, также как и Ваш `ConsoleApplication2.cpp`.

Возможно, понадобится переименовать эти файлы, чтобы Студия не запуталась, а то с ней бывает. Например, `edx-io.cpp` => `edx-io-plus.cpp`, и `edx-io.c => edx-io.cpp`.

**Comment by StudentIrgups** [comment]
Теперь вот что выводит:
[image: image.png]
Пробовал под ubuntu,тоже самое выводит.

вс, 24 февр. 2019 г. в 20:51, Maxim Buzdalov <notifications@github.com>:

**Comment by StudentIrgups** [comment]
[image: image.png]

вс, 24 февр. 2019 г. в 21:24, Алексей Безносов <beznosov.1992@gmail.com>:

**Comment by mbuzdalov** [comment]
Картинки не приложились.

**Comment by StudentIrgups** [comment]
Да вроде приложились...

вс, 24 февр. 2019, 21:29 Maxim Buzdalov <notifications@github.com>:

**Comment by StudentIrgups** [comment]
У меня ещё такая проблема возникла. На сайте openedu в Вашем первом уроке
по алгоритмам и структурам есть задача: Сортировка вставками, в общем для
одного и того же файла срр компилятор сайта показывает разные результаты,
например, выложил файл, показывает три теста пройдено, выложил тот же файл
чуть позже, показывает ни одного пройденного теста, не думаю, что проблема
в моем файлике.

вс, 24 февр. 2019, 23:12 Алексей Безносов <beznosov.1992@gmail.com>:

**Comment by mbuzdalov** [comment]
Ваши картинки, к сожалению, выглядят вот так:

Теперь вот что выводит:
[image: image.png]
Пробовал под ubuntu,тоже самое выводит.

В исходном коде страницы в этом месте тоже только текст, т.е. проблема не в том, что у меня в браузере что-то почему-то не грузится. Поэтому я ничего не могу видеть.

-------------------------

По второй проблеме - проблема, скорее всего, именно в Вашем коде, и почти наверняка - в выходе за границу массива. На каком тесте такой код упадет, зависит от кучи разных причин (например, от того, что было в той памяти, в которой расположился проблемный массив; какие переменные расположены рядом, и так далее), и это нормально, что с одним и тем же компилятором тесты, на которых все падает, могут быть разными.

Точнее смогу сказать, если узнаю Ваш логин. При написании сообщений на форуме это получается автоматически, а здесь - уж извините - логин Вам придется написать вручную :)

**Comment by StudentIrgups** [comment]
Доброго времени суток! Логин beznosov1992

вс, 24 февр. 2019, 23:47 Maxim Buzdalov <notifications@github.com>:

**Comment by StudentIrgups** [comment]
По поводу картинок которые не приложились, вот последняя:
![image](https://user-images.githubusercontent.com/47680334/53318343-4c12b600-3912-11e9-9391-11d0c78ea4aa.png)

**Comment by mbuzdalov** [comment]
Вот теперь понятно. Я попробую реализовать правильную обработку случая, когда проект собирается с поддержкой юникода (макросы `UNICODE` и `_UNICODE`).

Вы же, со своей стороны, если не хотите ждать, можете попробовать отключить юникод в своем проекте, тогда все будет собираться нормально. Но, пожалуй, лучше подождать :)

--------
По поводу сортировки вставками: да, это выход за границу массива, и вот он где:

```
    int64_t *mass = new int64_t[n];
 
    for (int i = 1; i <= n; i++) {
        fscanf(file, "%lld", &mass[i]);
        cout << mass[i] << endl;
    }
```

Такой массив принимает индексы от `0` до `n - 1`, а Вы индексируете от `1` до `n`. При обращении `mass[n]` код падает, если сразу за массивом расположена область памяти, доступная только для чтения. Ну или если сразу за ним лежат какие-нибудь значимые переменные программы, которые Вы, в этом случае, цинично переписываете, и программа падает немного погодя и с совершенно дикими симптомами.

**Comment by mbuzdalov** [comment]
Даже можно сделать вот так: попробуйте найти в Вашем файле `edx-io.cpp` вот эти строки:

```
            LPTSTR msg;
            DWORD symbol_cnt = FormatMessage(
                FORMAT_MESSAGE_FROM_SYSTEM | FORMAT_MESSAGE_ALLOCATE_BUFFER,
                0, // the optional message
                err,
                0, // the language: 0 means "guess on your own"
                (LPTSTR) &msg,
                0, // nSize which is ignored
                NULL // varargs which are not used
            );
```

и заменить два вхождения `LPTSTR` на `LPSTR`, а `FormatMessage` заменить на `FormatMessageA`. Если у Вас все соберется и заработает, я прямо эти исправления и внесу.

**Comment by StudentIrgups** [comment]
В общем добавил файлы в проект:
![image](https://user-images.githubusercontent.com/47680334/53410162-5a41fe80-3a06-11e9-877a-2462fc57d67c.png)
Нашел, вхождения которые надо было изменить(почему-то два выражения подчеркивает):
![image](https://user-images.githubusercontent.com/47680334/53410259-9ecd9a00-3a06-11e9-84b4-c450feec9e58.png)
После сделанного выше выводит ошибки при сборке:
![image](https://user-images.githubusercontent.com/47680334/53410303-c58bd080-3a06-11e9-997d-47e8f748b791.png)

**Comment by StudentIrgups** [comment]
FORMAT_MESSAGE_FROM_SYSTEM тоже подчеркивал, букву А уже я подставлял для теста.

**Comment by StudentIrgups** [comment]
Но, кстати, под ubuntu собрал, все работает замечательно. Есть возможность добавить мне пару попыток для задачи Сортировка вставками?

**Comment by mbuzdalov** [comment]
Судя по выдаваемой студией командной строке, она все еще пытается компилировать lesson3.cpp в одиночку, без каких-либо объектных файлов. Почему такое происходит, не знаю. Попробуйте приложить весь проект (заархивированный), быть может, я пойму, в чем там проблема.

За подтверждение работоспособности модификации спасибо, сейчас залью это изменение и обновлю файлы в тестирующей системе.

Число попыток по задаче "Сортировка вставками" поднял до ста.

**Comment by StudentIrgups** [comment]
Ссылка на архив проекта:
[https://drive.google.com/file/d/1FKAFPswdKjHOwEJbP0BU2c_GMXtlp9y0/view?usp=sharing](url)
Ссылку скопировать и вставить в строку браузера, если так кликнуть, то не работает.

**Comment by mbuzdalov** [comment]
Хм, правильно ли я понял, что Вы переписали командную строку студии, которая компилирует исходники, на свою? В файле `lessons3.vcxproj` есть два раза такое:

```xml
<NMakeBuildCommandLine>cl /O2 /TP /EHsc lessons3.cpp</NMakeBuildCommandLine>
```

что, собственно, и является проблемой. Там, по-хорошему, надо перечислить все плюсовые файлы, все три (`lessons3.cpp`, `edx-io.cpp`, `edx-io-plus.cpp`). Тогда оно должно все собирать.

А еще оно должно все собирать и без вписывания руками опций. Если Вы так боролись с precompiled headers, их можно вывинтить и "цивилизованным путем", просто найти соответствующие опции и отключить их (и в дебаге, и в релизе).

**Comment by StudentIrgups** [comment]
Включил в строку компиляции все файлы, заработало.
Спасибо за помощь и обвертки!
