### ISSUE TITLE
Не компилируется пример VS2017

### ISSUE THREAD

**Issue by somebody0q** [mbuzdalov/edx-io#5]
Добрый день! При попытке скомпилировать код с данной оберткой (файлы в папке с проектом, в проект добалены) получаю множество (50) ошибок компиляции. 
Мой код буквально следующий: 

```
#include <iostream>
#include <cstring>
#include <fstream>
#include "edx-io.hpp"

int main()
{
	int a, b;
	io >> a >> b;
	io << a + b << '\n';
	return 0;
}
```

И output вот такой
1>------ Build started: Project: W1T1_SimpleSum, Configuration: Debug Win32 ------
1>W1T1_SimpleSum.cpp
1>edx-io.obj : error LNK2005: "void __cdecl check_erange(char const *)" (?check_erange@@YAXPBD@Z) already defined in edx-io-plus.obj
1>edx-io.obj : error LNK2005: "char * __cdecl consume_token(int *,unsigned int *)" (?consume_token@@YAPADPAHPAI@Z) already defined in edx-io-plus.obj
1>edx-io.obj : error LNK2005: "char * __cdecl copy_string_contents(char const *,unsigned int)" (?copy_string_contents@@YAPADPBDI@Z) already defined in edx-io-plus.obj
1>edx-io.obj : error LNK2005: "void __cdecl edx_close_input(void)" (?edx_close_input@@YAXXZ) already defined in edx-io-plus.obj
1>edx-io.obj : error LNK2005: "void __cdecl edx_open_input(void)" (?edx_open_input@@YAXXZ) already defined in edx-io-plus.obj
1>edx-io.obj : error LNK2005: "int __cdecl i32_impl_safe(int,int,int)" (?i32_impl_safe@@YAHHHH@Z) already defined in edx-io-plus.obj
1>edx-io.obj : error LNK2005: "int __cdecl i64_impl_safe(__int64,int,int)" (?i64_impl_safe@@YAH_JHH@Z) already defined in edx-io-plus.obj
1>edx-io.obj : error LNK2005: "int __cdecl int_to_buffer(unsigned int,int)" (?int_to_buffer@@YAHIH@Z) already defined in edx-io-plus.obj
1>edx-io.obj : error LNK2005: "int __cdecl long_long_to_buffer(unsigned __int64,int)" (?long_long_to_buffer@@YAH_KH@Z) already defined in edx-io-plus.obj
1>edx-io.obj : error LNK2005: "void __cdecl print_windows_error_and_exit(void)" (?print_windows_error_and_exit@@YAXXZ) already defined in edx-io-plus.obj
1>edx-io.obj : error LNK2005: "void __cdecl skip_whitespace(void)" (?skip_whitespace@@YAXXZ) already defined in edx-io-plus.obj
1>edx-io.obj : error LNK2005: _edx_close already defined in edx-io-plus.obj
1>edx-io.obj : error LNK2005: _edx_next_bounded already defined in edx-io-plus.obj
1>edx-io.obj : error LNK2005: _edx_next_double already defined in edx-io-plus.obj
1>edx-io.obj : error LNK2005: _edx_next_i32 already defined in edx-io-plus.obj
1>edx-io.obj : error LNK2005: _edx_next_i64 already defined in edx-io-plus.obj
1>edx-io.obj : error LNK2005: _edx_next_unbounded already defined in edx-io-plus.obj
1>edx-io.obj : error LNK2005: _edx_open already defined in edx-io-plus.obj
1>edx-io.obj : error LNK2005: _edx_print already defined in edx-io-plus.obj
1>edx-io.obj : error LNK2005: _edx_print_char already defined in edx-io-plus.obj
1>edx-io.obj : error LNK2005: _edx_print_double already defined in edx-io-plus.obj
1>edx-io.obj : error LNK2005: _edx_print_i32 already defined in edx-io-plus.obj
1>edx-io.obj : error LNK2005: _edx_print_i64 already defined in edx-io-plus.obj
1>edx-io.obj : error LNK2005: _edx_print_ui32 already defined in edx-io-plus.obj
1>edx-io.obj : error LNK2005: _edx_print_ui64 already defined in edx-io-plus.obj
1>edx-io.obj : error LNK2005: _edx_printf already defined in edx-io-plus.obj
1>edx-io.obj : error LNK2005: _edx_println already defined in edx-io-plus.obj
1>edx-io.obj : error LNK2005: _edx_println_char already defined in edx-io-plus.obj
1>edx-io.obj : error LNK2005: _edx_println_double already defined in edx-io-plus.obj
1>edx-io.obj : error LNK2005: _edx_println_i32 already defined in edx-io-plus.obj
1>edx-io.obj : error LNK2005: _edx_println_i64 already defined in edx-io-plus.obj
1>edx-io.obj : error LNK2005: _edx_println_ui32 already defined in edx-io-plus.obj
1>edx-io.obj : error LNK2005: _edx_println_ui64 already defined in edx-io-plus.obj
1>edx-io.obj : error LNK2005: _edx_unsafe_read_token already defined in edx-io-plus.obj
1>edx-io.obj : error LNK2005: "char * mmap_buf" (?mmap_buf@@3PADA) already defined in edx-io-plus.obj
1>edx-io.obj : error LNK2005: "char * mmap_end" (?mmap_end@@3PADA) already defined in edx-io-plus.obj
1>edx-io.obj : error LNK2005: "char * mmap_ptr" (?mmap_ptr@@3PADA) already defined in edx-io-plus.obj
1>edx-io.obj : error LNK2005: "void * input_file_handle" (?input_file_handle@@3PAXA) already defined in edx-io-plus.obj
1>edx-io.obj : error LNK2005: "void * mapping" (?mapping@@3PAXA) already defined in edx-io-plus.obj
1>edx-io.obj : error LNK2005: "union _LARGE_INTEGER input_file_size" (?input_file_size@@3T_LARGE_INTEGER@@A) already defined in edx-io-plus.obj
1>edx-io.obj : error LNK2005: "struct _iobuf * ouf" (?ouf@@3PAU_iobuf@@A) already defined in edx-io-plus.obj
1>edx-io.obj : error LNK2005: "char * number_buffer" (?number_buffer@@3PADA) already defined in edx-io-plus.obj
1>edx-io.obj : error LNK2005: "int number_opened" (?number_opened@@3HA) already defined in edx-io-plus.obj
1>edx-io.obj : error LNK2005: "char * digit_tens" (?digit_tens@@3PADA) already defined in edx-io-plus.obj
1>edx-io.obj : error LNK2005: "char * digit_ones" (?digit_ones@@3PADA) already defined in edx-io-plus.obj
1>W1T1_SimpleSum.obj : error LNK2019: unresolved external symbol "public: struct edx_io const & __thiscall edx_io::operator>>(int &)const " (??5edx_io@@QBEABU0@AAH@Z) referenced in function _main
1>W1T1_SimpleSum.obj : error LNK2019: unresolved external symbol "public: struct edx_io const & __thiscall edx_io::operator<<(int)const " (??6edx_io@@QBEABU0@H@Z) referenced in function _main
1>W1T1_SimpleSum.obj : error LNK2019: unresolved external symbol "public: struct edx_io const & __thiscall edx_io::operator<<(char)const " (??6edx_io@@QBEABU0@D@Z) referenced in function _main
1>W1T1_SimpleSum.obj : error LNK2001: unresolved external symbol "struct edx_io io" (?io@@3Uedx_io@@A)
1>C:\Users\NALE\Desktop\Current\Personal\Programing\DataStructuresAndAlgoritms_\Week1\W1T1_SimpleSum\Debug\W1T1_SimpleSum.exe : fatal error LNK1120: 4 unresolved externals
1>Done building project "W1T1_SimpleSum.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
Помогите понять в чем проблема. Хотелось бы сразу начинать решать задачи в той манере, в которой я буду оформлять их по ходу курса (а не писать каждый раз свой ввод-вывод).

**Comment by mbuzdalov** [comment]
Не могли бы Вы приложить архив с проектом? Видно, что файлы `edx-io*.cpp` добавлены в проект криво, а как именно криво, сказать пока не могу.

**Comment by somebody0q** [comment]
[W1T1_SimpleSum.zip](https://github.com/mbuzdalov/edx-io/files/2910293/W1T1_SimpleSum.zip)

Добавлял через Project/Add Existing Item ...

**Comment by mbuzdalov** [comment]
А, все понятно. Вы перетерли плюсовый файл. У Вас `edx-io.cpp` и `edx-io-plus.cpp` - это один и тот же файл. Поэтому "плюсовые" функции не найдены, а "сишные" найдены по два раза.

**Comment by somebody0q** [comment]
Большое спасибо за пордсказку!
Корень этой проблемы в том что из вот этого места:
https://github.com/mbuzdalov/edx-io/tree/master/src/c++
качается ++ файл, но с расширением .с
И при переименовании получается 2 файла с одинаковым кодом и разными именами. 
Соседний топик имеет такую же проблему.

**Comment by somebody0q** [comment]
Большое спасибо за оперативный ответ и помощь!

**Comment by mbuzdalov** [comment]
Не до конца понял проблему.

По ссылке на `edx-io.c` в README качается сишный файл `edx-io.c`, по ссылке в списке файлов качается плюсовый файл `edx-io.cpp`. Проблемы в Visual Studio приводят к тому, что их нужно переименовать так, чтобы расширения были `*.cpp` у обоих файлов, и чтобы имена были разные (неважно какие).

Мне казалось, что приписка по поводу студии все это уже говорит без возможности неверного прочтения. Если это не так, посоветуйте, пожалуйста, как надо :)

P.S.: В соседнем топике немного другие проблемы с линковкой, там я с проектом еще не разбирался, ну и реальная проблема с юникодом тоже была обнаружена (и исправлена).

**Comment by somebody0q** [comment]
Я уже удалил свой некоректный коментарий  :-) Это была чистой воды моя ошибка! 
Еще раз большое спасибо!
