### ISSUE TITLE
Запись в файл в python 3.6

### ISSUE THREAD

**Issue by Aqice** [mbuzdalov/edx-io#7]
При исполнении следующего кода (как и любого другого с использованием writeln в цикле) метод игнорирует '\n':

with edx_io() as io:
    for _ in range(5):
        io.writeln(1)

Содержимое 'output.txt' после исполнения:
'11111'
Ожидаемый результат:
'1
1
1
1
1'

**Comment by mbuzdalov** [comment]
Это скорее баг программы Notepad :)

Сейчас `writeln` выводит юниксовый перевод строки (один символ, 0x0a, он же `\n`), в то время как виндовый перевод строки - два символа (0x0d 0x0a, `\r\n`).

В 21 веке подавляющее большинство программ (включая проверяющие программы, работающие на благо нашего курса у нас в тестирующей системе) отлично понимают любые варианты последовательности перевода строки (есть еще одинокий `\r` на старых Маках). Остался один Notepad, который вместо перевода строки в случае `\n` ничего не делает. Поэтому Вам кажется, что перевода строки нет. Можете открыть тот же файл программой WordPad и увидеть, что переводы строки там все же есть.

Чтобы не паниковать лишний раз, замените последнюю строку Вашей копии `edx_io.py` на вот эту:

    self.ouf.write(b"\r\n")

В глобальной копии я пока что ничего менять не буду, чтобы, например, не уменьшать производительности ваших решений в задачах, где надо вывести много маленьких строк.

**Comment by Aqice** [comment]
Понятно.
Спасибо за ответ!
